### ISSUE TITLE
How to change the font of the template?

### ISSUE THREAD

**Issue by yuw444** [maumneto/TemplateBeamerUFC#2]
Hi,

First of all, thanks for developing this amazing template, which will help me a lot. However, I am struggling to change the font of the template. For example, the "date" and table of contents "Sumário" are in Brazil. I'm using your overleaf template.  I tried 

`\RequirePackage[english]{babel}` 
`\documentclass[english]{libs/ufc_format}`
`\AtBeginDocument{\selectlanguage{english}}`

They only fixed the "date". So, please help.

Thanks so much.

**Comment by maumneto** [comment]
Hello!
First of all, thanks for the compliment! Sorry for the delay in responding to you. Part of the solution to this problem is what you said. However, in the ufc_format.cls file, you must modify several words for English. As this template is originally for UFC (Brazil) students/professors, I did not provide other languages for the fields. Let me know if you have any difficulty changing the fields to English to help you. Template improvement tips are also welcome. :)

**Comment by yuw444** [comment]
Thanks for your response, I will try my best to make it available in English. Of course, always credit to you.

**Comment by maumneto** [comment]
I thank you for using this template. Another thing that I remembered. The packages are in the preamble.tex file. Then you should change the babel package to English there as well.
